-- Make blog_posts.content support bilingual JSON ({"pt":"...","en":"..."})
-- This script updates the 3 existing articles from plain text to JSON
-- Can be rerun safely using ON CONFLICT or checking content type

-- Update approach: set content as JSON with both PT and EN versions
-- DO NOT use jsonb type for the column, just store JSON as text to avoid schema change

-- Article 1: Como Aprender Inglês Sozinho
UPDATE blog_posts SET content = '{"pt": "<h1>Como Aprender Ingles Sozinho: Guia Completo para Iniciantes</h1><p>Aprender ingles sozinho e totalmente possivel com as estrategias certas. Neste guia completo, voce vai descobrir <strong>como aprender ingles sozinho</strong> de forma eficiente, com recursos gratuitos e um plano de estudos passo a passo.</p><h2>1. Defina seus objetivos</h2><p>Antes de comecar, pergunte-se: por que voce quer aprender ingles? Ter metas claras ajuda a manter a motivacao.</p><h2>2. Crie uma rotina de estudos</h2><p>A consistencia e mais importante que a intensidade. Estude 30 minutos por dia, todos os dias.</p><h2>3. Use recursos variados</h2><p>Combine apps, videos, podcasts e leitura para trabalhar diferentes habilidades.</p><h2>4. Pratique a conversacao</h2><p>Nao tenha medo de errar. Fale desde o primeiro dia, mesmo que seja sozinho.</p><h2>5. Meca seu progresso</h2><p>Faca testes de nivel periodicamente para acompanhar sua evolucao.</p><p>Com disciplina e as ferramentas certas, a fluencia esta ao seu alcance!</p>", "en": "<h1>How to Learn English Alone: A Complete Guide for Beginners</h1><p>Learning English alone is entirely possible with the right strategies. In this complete guide, you will discover <strong>how to learn English alone</strong> efficiently, with free resources and a step-by-step study plan.</p><h2>1. Set your goals</h2><p>Before you start, ask yourself: why do you want to learn English? Having clear goals helps maintain motivation.</p><h2>2. Create a study routine</h2><p>Consistency is more important than intensity. Study 30 minutes a day, every day.</p><h2>3. Use varied resources</h2><p>Combine apps, videos, podcasts and reading to work on different skills.</p><h2>4. Practice conversation</h2><p>Dont be afraid to make mistakes. Speak from day one, even if alone.</p><h2>5. Measure your progress</h2><p>Take level tests periodically to track your evolution.</p><p>With discipline and the right tools, fluency is within your reach!</p>"}'::jsonb WHERE slug = 'como-aprender-ingles-sozinho';

-- Article 2: As 50 Frases em Inglês Mais Usadas
UPDATE blog_posts SET content = '{"pt": "<h1>As 50 Frases em Ingles Mais Usadas no Dia a Dia</h1><p>Conhecer as frases em ingles mais usadas no dia a dia e essencial para quem quer se comunicar com confianca. Neste artigo, voce vai aprender <strong>50 frases em ingles</strong> divididas por categorias.</p><h2>Saudacoes e Cortesia</h2><p>Good morning - Bom dia<br>Good afternoon - Boa tarde<br>Good evening - Boa noite (chegada)<br>How are you? - Como vai?<br>Fine, thanks - Bem, obrigado<br>Nice to meet you - Prazer em conhece-lo<br>See you later - Ate logo<br>Thank you - Obrigado<br>You are welcome - De nada<br>Excuse me - Com licenca</p><h2>Emergencias</h2><p>I need help - Preciso de ajuda<br>Call an ambulance - Chame uma ambulancia<br>Where is the hospital? - Onde fica o hospital?<br>I am lost - Estou perdido</p><p>Dominar essas frases vai transformar sua comunicacao em ingles!</p>", "en": "<h1>The 50 Most Used English Phrases in Daily Life</h1><p>Knowing the most used English phrases in daily life is essential for anyone who wants to communicate with confidence. In this article, you will learn <strong>50 English phrases</strong> divided by categories.</p><h2>Greetings and Courtesy</h2><p>Good morning<br>Good afternoon<br>Good evening<br>How are you?<br>Fine, thanks<br>Nice to meet you<br>See you later<br>Thank you<br>You are welcome<br>Excuse me</p><h2>Emergencies</h2><p>I need help<br>Call an ambulance<br>Where is the hospital?<br>I am lost</p><p>Mastering these phrases will transform your English communication!</p>"}'::jsonb WHERE slug = 'frases-em-ingles-mais-usadas';

-- Article 3: Inglês para Viagem
UPDATE blog_posts SET content = '{"pt": "<h1>Ingles para Viagem: 50 Palavras e Expressoes Essenciais</h1><p>Viajar para um pais de lingua inglesa e muito mais facil quando voce conhece o vocabulario basico. Neste guia de <strong>ingles para viagem</strong>, voce vai aprender as palavras e expressoes essenciais.</p><h2>No Aeroporto</h2><p>Passport - Passaporte<br>Boarding pass - Cartao de embarque<br>Check-in - Check-in<br>Departure lounge - Sala de embarque<br>Gate - Portao de embarque</p><h2>No Restaurante</h2><p>I would like to order - Gostaria de pedir<br>The bill, please - A conta, por favor<br>Is service included? - O servico esta incluido?<br>I am allergic to... - Tenho alergia a...</p><p>Com essas palavras, sua viagem sera muito mais tranquila!</p>", "en": "<h1>English for Travel: 50 Essential Words and Phrases</h1><p>Traveling to an English-speaking country is much easier when you know basic vocabulary. In this <strong>English for travel</strong> guide, you will learn essential words and phrases.</p><h2>At the Airport</h2><p>Passport<br>Boarding pass<br>Check-in<br>Departure lounge<br>Gate</p><h2>At the Restaurant</h2><p>I would like to order<br>The bill, please<br>Is service included?<br>I am allergic to...</p><p>With these words, your trip will be much smoother!</p>"}'::jsonb WHERE slug = 'ingles-para-viagem';
